version: "3"

services:
  nginx:
    depends_on:
      - application
      - postgres
    links:
      - application
      - postgres
    build:
      context: .
      target: nginx_revproxy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - reverse

  application:
    container_name: application
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    ports:
      - "3000"
      - "3001"
    volumes:
      - ./src:/app
    networks:
      - reverse

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital_middleware
    ports:
      - "5432:5432"
    restart: unless-stopped
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    networks:
      - reverse

# volumes:
#   postgres_data:
#     external: true

networks:
  reverse:
    driver: bridge
