version: "3"

services:
  nginx:
    depends_on:
      - hospital_a
      - hospital_b
      - postgres
    links:
      - hospital_a
      - hospital_b
      - postgres
    build:
      context: .
      target: nginx_revproxy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - reverse

  hospital_a:
    container_name: hospital_a
    environment:
      - HOSPITAL_NAME=A
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    ports:
      - "3000"
    volumes:
      - ./src:/app
    networks:
      - reverse

  hospital_b:
    container_name: hospital_b
    environment:
      - HOSPITAL_NAME=B
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    ports:
      - "3000"
    volumes:
      - ./src:/app
    networks:
      - reverse

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital_middleware
      POSTGRES_PORT: 3000
    ports:
      - "3000"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - reverse

# volumes:
#   postgres_data:
#     external: true

networks:
  reverse:
    driver: bridge
